import test from 'node:test';
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { chromium } from 'playwright';
import { loadConfig } from '../src/config.js';
import { loadLanguagePacks } from '../src/i18n.js';
import { configureDataSaver, dataSaverHtml } from '../src/data-saver.js';

test('100 KB/s visitors can use the waiting-screen switch before parsing finishes without downloading media or engines', { timeout:30000 }, async () => {
  const config = await loadConfig(process.cwd());
  await loadLanguagePacks(config);
  config.site.dataSaver = { enabled:true, debug:false, mode:'auto', detectSlowConnection:true, respectBrowserPreference:false, promptAfterMs:5000 };
  await configureDataSaver(config);
  const runtime = await readFile('static/edgepress/data-saver.js');
  const css = await readFile('static/edgepress/data-saver.css');
  const html = dataSaverHtml('<html lang="zh-CN"><head><meta charset="utf-8"><link rel="stylesheet" href="/full.css"><script defer src="/engine.js" data-data-optional></script></head><body><header><nav><a href="/second/">下一頁</a></nav></header><main><h1>可閱讀的文章</h1><p>文字內容與網站導航。</p><img src="/large.png" alt="圖像描述"></main><footer>獨立頁腳</footer></body></html>',config);
  const requests = [];
  const timers = new Set();
  const server = createServer((request,response) => {
    const path = new URL(request.url,'http://localhost').pathname;
    requests.push(path);
    response.setHeader('Cache-Control','no-store');
    if (path.endsWith('.js')) return response.writeHead(200,{'Content-Type':'text/javascript'}).end(runtime);
    if (path.endsWith('.css')) return response.writeHead(200,{'Content-Type':'text/css'}).end(path === '/full.css' ? 'body{margin:0}' + '/*' + 'x'.repeat(600000) + '*/' : css);
    if (path.endsWith('.png')) return response.writeHead(200,{'Content-Type':'image/png'}).end(Buffer.alloc(1000000));
    const split = html.indexOf('<header>');
    response.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});
    response.write(html.slice(0,split));
    const timer = setTimeout(() => { timers.delete(timer); response.end(html.slice(split)); },1500);
    timers.add(timer);
    response.on('close',() => { clearTimeout(timer); timers.delete(timer); });
  });
  await new Promise(resolve => server.listen(0,'127.0.0.1',resolve));
  const browser = await chromium.launch({headless:true,args:['--disable-extensions']});
  try {
    const context = await browser.newContext({viewport:{width:390,height:844},colorScheme:'dark'});
    await context.addInitScript(() => Object.defineProperty(navigator,'connection',{get:() => ({saveData:true,effectiveType:'2g'})}));
    const page = await context.newPage();
    const session = await context.newCDPSession(page);
    await session.send('Network.enable');
    await session.send('Network.emulateNetworkConditions',{offline:false,latency:150,downloadThroughput:100*1024,uploadThroughput:100*1024});
    const started = performance.now();
    await page.goto('http://127.0.0.1:' + server.address().port,{waitUntil:'commit'});
    const button = page.locator('[data-data-mode=text]');
    await button.waitFor({state:'visible'});
    const offeredAfterMs = Math.round(performance.now()-started);
    assert(offeredAfterMs < 1500,'Waiting entry must not wait for HTML completion: ' + offeredAfterMs);
    assert.equal(await page.evaluate(() => document.readyState),'loading');
    assert.equal(await page.getAttribute('html','data-edgepress-data-mode'),'full');
    assert.equal(await page.locator('[data-data-progress]').isVisible(),true);
    assert(!requests.includes('/full.css'));
    await button.focus();
    await Promise.all([page.waitForNavigation({waitUntil:'domcontentloaded'}),page.keyboard.press('Enter')]);
    await page.waitForFunction(() => document.documentElement.dataset.edgepressDataReady === 'true');
    const readableAfterMs = Math.round(performance.now()-started);
    assert(readableAfterMs < 6000,'Text reading must not wait ten seconds: ' + readableAfterMs);
    assert.equal(await page.locator('main').isVisible(),true);
    assert.equal(await page.locator('header nav').isVisible(),true);
    assert.equal(await page.locator('footer').innerText(),'獨立頁腳');
    assert.match(await page.locator('main').innerText(),/圖像描述/);
    assert(!requests.some(path => ['/full.css','/large.png','/engine.js'].includes(path)),requests.join('\n'));
    assert.equal(await page.evaluate(() => document.activeElement.tagName),'MAIN');
    console.log(JSON.stringify({bandwidthKBs:100,latencyMs:150,offeredAfterMs,readableAfterMs,requests}));
    await context.close();
    requests.length = 0;
    const pending = await browser.newContext({viewport:{width:390,height:844},colorScheme:'light'});
    const loadingPage = await pending.newPage();
    const loadingSession = await pending.newCDPSession(loadingPage);
    await loadingSession.send('Network.enable');
    await loadingSession.send('Network.emulateNetworkConditions',{offline:false,latency:150,downloadThroughput:100*1024,uploadThroughput:100*1024});
    await loadingPage.goto('http://127.0.0.1:' + server.address().port,{waitUntil:'domcontentloaded'});
    await loadingPage.waitForFunction(() => document.querySelector('[data-data-progress]').max >= 3);
    assert(requests.includes('/full.css'));
    assert.equal(await loadingPage.locator('[data-data-mode=text]').isVisible(),true);
    assert.match(await loadingPage.locator('[data-data-progress-label]').innerText(),/页面样式/);
    assert.equal(await loadingPage.getAttribute('html','data-edgepress-data-mode'),'full');
    const switchStarted = performance.now();
    await Promise.all([loadingPage.waitForNavigation({waitUntil:'domcontentloaded'}),loadingPage.locator('[data-data-mode=text]').click()]);
    await loadingPage.locator('main').waitFor({state:'visible'});
    const switchAfterMs = Math.round(performance.now()-switchStarted);
    assert(switchAfterMs < 6000,'Pending full CSS must not delay the text switch: ' + switchAfterMs);
    assert(!requests.includes('/large.png'));
    assert(!requests.includes('/engine.js'));
    console.log(JSON.stringify({pendingFullStyleSwitchAfterMs:switchAfterMs}));
    await pending.close();
  } finally {
    await browser.close();
    for (const timer of timers) clearTimeout(timer);
    server.closeAllConnections();
    await new Promise(resolve => server.close(resolve));
  }
});
